apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::623635142468:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1OBHXGDSZCR02
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::623635142468:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-07-30T14:54:39Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "56290"
  uid: 57bd3ff8-b8fe-4c8c-a4bf-a550775e2ddd
